import React from 'react';
import GlassCard from '../glass-ui/GlassCard';

const ResumePreview = ({ data, template }) => {
  return (
    <GlassCard hover={false}>
      <div style={styles.preview}>
        <div style={styles.header}>
          <h2 style={styles.name}>{data.personalInfo.name || 'Your Name'}</h2>
          <div style={styles.contact}>
            {data.personalInfo.email && <span>{data.personalInfo.email}</span>}
            {data.personalInfo.phone && <span> | {data.personalInfo.phone}</span>}
          </div>
        </div>

        {data.summary && (
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>Professional Summary</h3>
            <p style={styles.text}>{data.summary}</p>
          </div>
        )}

        {data.skills.length > 0 && (
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>Skills</h3>
            <div style={styles.skillsList}>
              {data.skills.map((skill, index) => (
                <span key={index} style={styles.skill}>{skill}</span>
              ))}
            </div>
          </div>
        )}

        <div style={styles.watermark}>
          Generated by PlacePrep AI
        </div>
      </div>
    </GlassCard>
  );
};

const styles = {
  preview: {
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#1a1a1a',
    padding: '40px',
    borderRadius: '8px',
    minHeight: '600px',
    position: 'relative'
  },
  header: {
    borderBottom: '2px solid #667eea',
    paddingBottom: '16px',
    marginBottom: '24px'
  },
  name: {
    fontSize: '32px',
    fontWeight: '900',
    color: '#1a1a1a',
    marginBottom: '8px'
  },
  contact: {
    fontSize: '14px',
    color: '#666'
  },
  section: {
    marginBottom: '24px'
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#667eea',
    marginBottom: '12px',
    textTransform: 'uppercase',
    letterSpacing: '1px'
  },
  text: {
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#333'
  },
  skillsList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px'
  },
  skill: {
    padding: '4px 12px',
    background: '#667eea',
    color: 'white',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '600'
  },
  watermark: {
    position: 'absolute',
    bottom: '20px',
    right: '40px',
    fontSize: '10px',
    color: '#999',
    fontStyle: 'italic'
  }
};

export default ResumePreview;
